# the "numpy" module

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [6]:
import numpy as np

a = np.array([1, 2, 3])   
print(type(a))            
print(a.shape)            
print(a[0], a[1], a[2])           

<class 'numpy.ndarray'>
(3,)
1 2 3


In [5]:
a[0] = 5                  
print(a)  

[5 2 3]


In [7]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b.shape)                 
print(b[0, 0], b[1, 0], b[2, 0])

(3, 3)
1 4 7


Numpy also provides many functions to create arrays with data:

In [8]:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)                    

[[0. 0.]
 [0. 0.]]


In [9]:
b = np.ones((1,2))    # Create an array of all ones
print(b) 

[[1. 1.]]


In [10]:
c = np.full((2,2), 7)  # Create a constant array
print(c) 

[[7 7]
 [7 7]]


In [11]:
d = np.eye(3)         # Create a 2x2 identity matrix
print(d)              

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
e = np.random.random((2,2))  # Create an array filled with random values
print(e) 

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [14]:
import numpy as np

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

print()  # just to get an empty line between the two datasets

b = a[:2, 1:3]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[2 3]
 [6 7]]


A slice of an array is a view into the same data, so modifying it
will modify the original array.

In [17]:
print(a[0, 1])   
b[0, 0] = 77     
print(a[0,1])
print()
print(a)

77
77

[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Access to a single row
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  
print() # just ean empty line
print(row_r2, row_r2.shape)  


[5 6 7 8] (4,)

[[5 6 7 8]] (1, 4)


In [16]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  
print()
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


### integer array indexing

In [22]:
import numpy as np

a = np.array([[11,12,13], [21,22,23], [31,32,33]])
print (a)
print()
# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  



[[11 12 13]
 [21 22 23]
 [31 32 33]]

[11 22 31]


In [23]:
# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  

[11 22 31]


In [20]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]]) 

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]])) 

[12 12]
[12 12]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [24]:
import numpy as np

# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [27]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # np.arange creates an array of range 4 = [0,1,2,3]

[ 1  6  7 11]


In [29]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [32]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
print()

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      



[[1 2]
 [3 4]
 [5 6]]

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [33]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx

print(a[bool_idx])  
print()

# We can do all of the above in a single concise statement:
print(a[a > 2])   

[3 4 5 6]

[3 4 5 6]


## Datatypes
Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [19]:
import numpy as np

x = np.array([1, 2])   
print(x.dtype)         

x = np.array([1.0, 2.0])  
print(x.dtype)             

x = np.array([1, 2], dtype=np.int64) 
print(x.dtype)           

int32
float64
int64


## Array math
Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [34]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print()
print(y)
print()


[[1. 2.]
 [3. 4.]]

[[5. 6.]
 [7. 8.]]

[[ 6.  8.]
 [10. 12.]]

[[ 6.  8.]
 [10. 12.]]


In [ ]:
#  elementwise sum

print(np.add(x, y))
print()
print(x + y)   

In [ ]:
# Elementwise difference; both produce the array
print(x - y)
print()
print(np.subtract(x, y))

In [ ]:
# Elementwise product; both produce the array
print(x * y)
print()
print(np.multiply(x, y))

In [ ]:
# Elementwise division; both produce the array
print(x / y)
print()
print(np.divide(x, y))

In [ ]:
# Elementwise square root; produces the array
print(np.sqrt(x))

#### dot function
Note that unlike MATLAB, * is elementwise multiplication, not matrix multiplication. We instead use the [dot] function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. [dot] is available both as a function in the numpy module and as an instance method of array objects:

In [43]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

print(x)
print()
print(y)
print() 
print(x*y)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[ 5 12]
 [21 32]]


# vec


In [42]:
# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))
print()

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print()

# Matrix / matrix product; both produce the rank 2 array
print(x)
print()
print(y)
print()
print(x.dot(y))
print(np.dot(x, y))

219
219

[29 67]
[29 67]

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


#### sum

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements
print(np.sum(x, axis=0))  # Compute sum of each column
print(np.sum(x, axis=1))  # compute sum of each row

#### transposing (T)
Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [22]:
import numpy as np

x = np.array([[1,2], [3,4]])
print(x)    
print()
print(x.T) 

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [ ]:
# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    
print(v.T)

## Broadcasting
Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

This works; however when the matrix x is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix x is equivalent to forming a matrix vv by stacking multiple copies of v vertically, then performing elementwise summation of x and vv. We could implement this approach like this:

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 


y = x + vv  # Add x and vv elementwise
print(y)  

Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:


In [23]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line y = x + v works even though x has shape (4, 3) and v has shape (3,) due to broadcasting; this line works as if v actually had shape (4, 3), where each row was a copy of v, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

(1) If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.

(2) The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.

(3) The arrays can be broadcast together if they are compatible in all dimensions.

(4) After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.

(5) In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the documentation.

Here are some applications of broadcasting:

In [ ]:
import numpy as np

# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w
print(np.reshape(v, (3, 1)) * w)


In [ ]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3)
print(x + v)

In [ ]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. 
print((x.T + w).T)

In [ ]:
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

In [ ]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3)
print(x * 2)